### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by mazunki** [staticshock/colored-traceback.py#16]
# Problem 

I was running the `python -m colored_traceback script.py` command, but no output was shown to the terminal. I was getting error messages without adding the module, so I knew it wasn't working.

I figured out how to fix it by adding the hook manually from inside the script, as suggested:
```py
import colored_traceback
colored_traceback.add_hook()
```
I then got an error message:
```py
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/mazunki/.local/lib/python3.8/site-packages/colored_traceback/colored_traceback.py", line 27, in colorize_traceback
    tb_colored = pygments.highlight(tb_text, lexer, self.formatter)
  File "/home/mazunki/.local/lib/python3.8/site-packages/colored_traceback/colored_traceback.py", line 32, in formatter
    colors = _get_term_color_support()
  File "/home/mazunki/.local/lib/python3.8/site-packages/colored_traceback/colored_traceback.py", line 66, in _get_term_color_support
    curses.setupterm()
_curses.error: setupterm: could not find terminal
```

# (half-working) Solution

The reason I was getting no output was because I am using Alacritty, a custom terminal, and my `$TERM` variable was set to `alacritty`. Changing this as 
```bash
TERM=linux python script.py
# or
TERM=xterm-256color python script.py
```
solves the issue for imports, allowing you to view the colored traceback, but it still doesn't print anything by importing the module.

## Conclusion

I think either the module should forward the hook traceback to the user, or at least print a message saying that Curses failed to find a proper terminal; instead of just doing nothing.

PS: Also, @Alacritty, why do they even change `$TERM` when it leads to issues like these all over the place...? Can't even use `ssh(1)` without overriding TERM.

**Comment by PopeyedLocket** [comment]
i ran into the same issue. im using Konsole on manjaro. after installing with pip i just put this in `~/.bashrc`:
`alias python='TERM=xterm-256color python'`

**Comment by mazunki** [comment]
@PopeyedLocket At the time I opened this issue, Alacritty's terminfo wasn't very established under people's `/usr/share/terminfo/`, thus `infocmp alacritty` would say something along the lines of `infocmp: couldn't open terminfo file /usr/share/terminfo/a/alacritty`.

It's weird that Konsole's terminfo doesn't exist under Manjaro, but nothing surprises me from a [broken OS](https://manjarno.snorlax.sh/).

Regardless, you might have some luck by making a copy of the xterm-256colorterminfo entry: `infocmp xterm-256color > /usr/share/k/konsole`. Perhaps `vt100` is better than `xterm-256color`, since that's what Konsole is based on.

This is probably not a complete set of terminal codes, but I'm unable to find a better source. The better solution is to install a real OS.

**Comment by PopeyedLocket** [comment]
"real"? good god .. some programmers are so opinionated. manjaro works [great](https://www.youtube.com/watch?v=dQw4w9WgXcQ)!
