### ISSUE TITLE
colored-traceback or colored_traceback? Make up your mind

### ISSUE THREAD

**Issue by blshkv** [staticshock/colored-traceback.py#18]
the package called with '-' in most of the cases except the actual usage ```export colored_traceback *```
```pip install colored-traceback```
but module is installed as 
```colored_traceback```

This is confusing. Please make it everywhere the same.

**Comment by EpicWink** [comment]
You can do `pip install colored_traceback` if you wish: `pip` will normalise the name for installation. Python module and package names must only contain underscores `_`, so the import name must always be `import colored_traceback`.

**Comment by blshkv** [comment]
oh well. I tried ;-)
