### ISSUE TITLE
An option/argument to define a formatter.

### ISSUE THREAD

**Issue by feluxe** [staticshock/colored-traceback.py#5]
Hi there,

this module really helps me debugging! Thanks for sharing!

I just noticed that the `terminal` formatter looks much nicer in my terminal compared to the `terminal256` formatter. May I send you a PR with an implementation for an option that let's you pick a formatter?

**Comment by staticshock** [comment]
Sure. Could it be something like `--colors=16`, with the options being 16 or 256?

**Comment by feluxe** [comment]
Yes sure,  I make a PR then :)

**Comment by batisteo** [comment]
I’m actually in favor on making the `terminal` as default, as it looks much more "native".
I’ve got a nice 2×8 color pallette, and the default pygment colors for Python are not that pretty.
